CREATE TABLE 
TASKS(
TASK_ID INT NOT NULL AUTO_INCREMENT,
TASK_NAME VARCHAR(100),
TASK_DESCRIPTION VARCHAR(300),
TASK_ASSIGNEE_ID_PRIMARY VARCHAR(32),
PERCENTAGE_COMPLETED INT3,
PLANNED_DATE_START DATE,
PLANNED_START_TIME TIME,
PLANNED_DATE_END DATE,
PLANNED_END_TIME TIME,
ORDER_NO INT,
PRIORITY INT,
DIFFICULTY INT,
DEPENDING_ON_THIRD_PARTY BOOL,
TASK_STATUS_ID INT,
USER_ID_CREATED VARCHAR(32),
DATETIME_CREATED DATETIME,
USER_ID_UPDATED VARCHAR(32),
DATETIME_UPDATED DATETIME,
PRIMARY KEY (TASK_ID));

SELECT * FROM TASKS;

INSERT INTO TASKS
(TASK_NAME ,
TASK_DESCRIPTION ,
TASK_ASSIGNEE_ID_PRIMARY ,
PERCENTAGE_COMPLETED ,
PLANNED_DATE_START ,
PLANNED_START_TIME ,
PLANNED_DATE_END ,
PLANNED_END_TIME ,
ORDER_NO ,
PRIORITY ,
DIFFICULTY ,
DEPENDING_ON_THIRD_PARTY ,
TASK_STATUS_ID ,
USER_ID_CREATED ,
DATETIME_CREATED ,
USER_ID_UPDATED ,
DATETIME_UPDATED)
VALUES
('Creating first column',
'Creating new column to show all tasks and grab them with Flask',
'WojciechGeneratedID',
100,
DATE('2018-01-26'),
TIME('22:08'),
DATE('2018-01-26'),
TIME('23:08'),
1,
1,
1,
true,
1,
'WojciechGeneratedID',
SYSDATE(),
null,
null
);


INSERT INTO TASKS
(TASK_NAME ,
TASK_DESCRIPTION ,
TASK_ASSIGNEE_ID_PRIMARY ,
PERCENTAGE_COMPLETED ,
PLANNED_DATE_START ,
PLANNED_START_TIME ,
PLANNED_DATE_END ,
PLANNED_END_TIME ,
ORDER_NO ,
PRIORITY ,
DIFFICULTY ,
DEPENDING_ON_THIRD_PARTY ,
TASK_STATUS_ID ,
USER_ID_CREATED ,
DATETIME_CREATED ,
USER_ID_UPDATED ,
DATETIME_UPDATED)
VALUES
('Grab the data with Flask',
'Creating new column to show all tasks and grab them with Flask',
'WojciechGeneratedID',
100,
DATE('2018-01-26'),
TIME('22:09'),
DATE('2018-01-26'),
TIME('23:18'),
1,
1,
1,
true,
1,
'WojciechGeneratedID',
SYSDATE(),
null,
null
);


CREATE TABLE USERS
(USER_ID INT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(50),
SURNAME VARCHAR(50),
EMAIL VARCHAR(100), 
PHONE_NUMBER VARCHAR(20),
DEPARTMENT_ID INT,
ROLE_ID INT, 
USER_PASSWORD BLOB,
USER_ID_CREATED INT,
CREATED_DATETIME DATETIME);

# TESTING THE TABLE
INSERT INTO USERS
(FIRST_NAME,
SURNAME,
USER_PASSWORD,
CREATED_DATETIME)
VALUES
('Wojciech',
'Orzechowski',
'password',
SYSDATE());

SELECT * FROM USERS;

CREATE TABLE ROLES
(ROLE_ID INT AUTO_INCREMENT PRIMARY KEY,
ROLE_NAME VARCHAR(50),
ROLE_DESCRIPTION VARCHAR(300),
PERMISSION_ID INT,
USER_ID_CREATED INT,
CREATED_DATETIME DATETIME,
USER_ID_UPDATED INT,
UPDATED_DATETIME DATETIME
);

